### ISSUE TITLE
debrief  plugin |  dependency issue  | LXML

### ISSUE THREAD

**Issue by darmado** [armadoinc/sandcat#1]
**Describe the bug**
lxml dependency fails to compile on Python 3.13 due to compatibility issues with internal Python C API changes. This prevents installation of Caldera dependencies and breaks the debrief plugin functionality.

**To Reproduce**
1. Install Python 3.13.3
2. Create virtual environment with `python3 -m venv venv`
3. Activate environment with `source venv/bin/activate`
4. Run `pip install -r requirements.txt`
5. Installation fails during lxml compilation with multiple C compilation errors

**Expected behavior**
All dependencies should install successfully without compilation errors, allowing Caldera to run with full plugin functionality.

**Error Details**
Compilation fails with errors including:
- `call to undeclared function '_PyInterpreterState_GetConfig'`
- `call to undeclared function '_PyDict_SetItem_KnownHash'`
- `too few arguments to function call` for `_PyLong_AsByteArray`
- Multiple other internal Python C API compatibility issues

**Raw Error Output**
```
src/lxml/etree.c:5988:39: error: call to undeclared function '_PyInterpreterState_GetConfig'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    __pyx_assertions_enabled_flag = ! _PyInterpreterState_GetConfig(__Pyx_PyThreadState_Current->interp)->optimization_level;
                                      ^
src/lxml/etree.c:5988:107: error: member reference type 'int' is not a pointer
    __pyx_assertions_enabled_flag = ! _PyInterpreterState_GetConfig(__Pyx_PyThreadState_Current->interp)->optimization_level;
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
src/lxml/etree.c:255376:7: error: call to undeclared function '_PyDict_SetItem_KnownHash'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  if (__Pyx_SetNameInClass(__pyx_t_2, __pyx_n_s_getitem, __pyx_t_9) < 0) __PYX_ERR(0, 97, __pyx_L1_error)
      ^
src/lxml/etree.c:6652:38: note: expanded from macro '__Pyx_SetNameInClass'
    (likely(PyDict_CheckExact(ns)) ? _PyDict_SetItem_KnownHash(ns, name, value, ((PyASCIIObject *) name)->hash) : PyObject_SetItem(ns, name, value))
                                     ^
src/lxml/etree.c:264446:13: error: call to undeclared function '_PyUnicode_FastCopyCharacters'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
            _PyUnicode_FastCopyCharacters(result_uval, char_pos, uval, 0, ulength);
            ^
src/lxml/etree.c:269068:70: error: too few arguments to function call, expected 6, have 5
                                              is_little, !is_unsigned);
                                                                     ^
/usr/local/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13/cpython/longobject.h:111:17: note: '_PyLong_AsByteArray' declared here
PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
                ^
15 errors generated.
Compile failed: command '/usr/bin/clang' failed with exit code 1
error: command '/usr/bin/clang' failed with exit code 1
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for lxml
Running setup.py clean for lxml
Failed to build lxml
ERROR: Failed to build installable wheels for some pyproject.toml based projects (lxml)
```

**Desktop (please complete the following information):**
 - OS: macOS 13.0 (Darwin 22.6.0)
 - Python Version: 3.13.3
 - lxml Version: 4.9.1

**Workaround Applied**
- Disabled debrief plugin in `conf/default.yml`
- Commented out lxml dependency in `requirements.txt`
- This allows Caldera to run without debrief functionality

**Additional context**
The issue is caused by lxml not yet supporting Python 3.13's internal C API changes. The debrief plugin depends on lxml for XML parsing and report generation. Until lxml releases Python 3.13 compatible version, the debrief plugin must remain disabled or users should use Python 3.11/3.12.
